"""initial

Revision ID: 2acdc0783f81
Revises:
Create Date: 2025-02-25 15:15:49.711482

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2acdc0783f81"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "devices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "_status",
            sa.Enum("Parked", "Moving", "Idling", "Offline", name="devicestatus"),
            nullable=True,
        ),
        sa.Column("time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("unique_id", sa.String(), nullable=False),
        sa.Column("position_id", sa.Integer(), nullable=True),
        sa.Column("odometer", sa.Float(), nullable=True),
        sa.Column("moved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("stoped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("battery", sa.Float(), nullable=True),
        sa.Column("charging", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "positions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("speed", sa.Float(), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("course", sa.String(), nullable=True),
        sa.Column("altitude", sa.Float(), nullable=True),
        sa.Column("distance", sa.Float(), nullable=True),
        sa.Column("_address", sa.String(), nullable=True),
        sa.Column("protocol", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("positions")
    op.drop_table("devices")
    # ### end Alembic commands ###
