name: 'system-two'
type: ihs
direction: out
interval: "* * * * *"
timeout: 10
url:
  base: 'https://api.ihstowers.com'
  auth: 'https://login.microsoftonline.com/5dadcdcb-ea32-47fe-84b2-0f6cc63c2e0f/oauth2/v2.0/token' # Optional
  forward: '/process/api/message' # Optional
auth:
  type: token
  token_key: 'Authorization'
  token_type: 'bearer'
  headers:
    'content-type': 'application/json'
headers:
  'content-type': 'application/json'

