name: 'system-two'
type: ihs
direction: out
interval: 30
timeout: 10
url:
  base: 'http://localhost:3000'
  auth: '/api/session' # Optional
  position: '/api/positions' # Optional
auth:
  type: token
  token_key: 'Authorization'
  token_type: 'bearer'
  token: 'AUTH_TOKEN_ONE'
headers:
  'content-type': 'application/json'


