name: 'ingest-one'
enable: true
persist: false
type: wox # wox, traccar, http
direction: in # in | out
interval: "* * * * *"
timeout: 10
address: 'https://app.protrack.ng'
auth:
  type: form # basic | token | form
  username: 'als@tracking.com' # Optional | FROM: ENV_VAR
  password: 'secure@1234' # Optional | FROM: ENV_VAR
headers: # Optional
  'content-type': 'application/json'
