name: 'outro-one'
type: ihs
enable: true
direction: out
interval: "* * * * *"
timeout: 10
address: 'https://api.ihstowers.com'
auth:
  type: token
  token_key: 'Authorization'
  token_type: 'bearer'
  headers:
    'content-type': 'application/json'
headers: # Optional
  'content-type': 'application/json'
endpoints:
  login: # Optional
    auth: false
    path: 'https://login.microsoftonline.com/5dadcdcb-ea32-47fe-84b2-0f6cc63c2e0f/oauth2/v2.0/token'
    headers: {}
  position:
    auth: true
    path: '/process/api/message'
    headers: {}
